### ISSUE TITLE
composer install --no-dev fails during cache:clear

### ISSUE THREAD

**Issue by tvdijen** [OpenConext/Stepup-Middleware#317]
2021-01-28T12:06:06+01:00 [critical] Uncaught Error: Class 'Liip\TestFixturesBundle\LiipTestFixturesBundle' not found

**Comment by phavekes** [comment]
Tim, what version of php and composer are you using?

**Comment by tvdijen** [comment]
php74 & composerv1 ... But that should not be relevant here.
The problem is that Liip is listed as a dev-dependency, so it's not available when running composer with `--no-dev`

**Comment by tvdijen** [comment]
I've confirmed that the exact same issue exists with php72.  composerv2 isn't usable at all on this repo.
